#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.
# Makefile调用usys.pl（perl脚本）生成usys.S

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";      # 通过设置寄存器a7的值，表明调用哪个system call
    print " ecall\n";     # ecall表示一种特殊的trap，转到kernel/syscall.c:syscall执行
    print " ret\n";
}

#  trace:		# 定义用户态跳板函数
#  li a7, SYS_trace	# 将系统调用 id 存入 a7 寄存器
#  ecall       # ecall，调用 system call ，跳到内核态的统一系统调用处理函数 syscall()  (syscall.c)
#  ret
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");     # here
entry("sysinfo");     # here